<?php
/**
 * CheckoutFormFulfillmentShipmentSummaryLineItemsSent
 *
 * PHP version 5
 *
 * @category Class
 * @package  AllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AllegroApi\Model;
use \AllegroApi\ObjectSerializer;

/**
 * CheckoutFormFulfillmentShipmentSummaryLineItemsSent Class Doc Comment
 *
 * @category Class
 * @description Indicates how many line items have tracking number specified.
 * @package  AllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckoutFormFulfillmentShipmentSummaryLineItemsSent
{
    /**
     * Possible values of this enum
     */
    const NONE = 'NONE';
    const SOME = 'SOME';
    const ALL = 'ALL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::SOME,
            self::ALL,
        ];
    }
}


