<?php
/**
 * DisputesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl
 *
 * OpenAPI spec version: 1.0
 * Contact: api@allegro.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DisputesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DisputesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for saleDisputeAttachmentsAttachmentIdGet
     *
     * Get an attachment.
     *
     */
    public function testSaleDisputeAttachmentsAttachmentIdGet()
    {
    }

    /**
     * Test case for saleDisputeAttachmentsPost
     *
     * Post an attachment declaration.
     *
     */
    public function testSaleDisputeAttachmentsPost()
    {
    }

    /**
     * Test case for saleDisputesDisputeIdGet
     *
     * Get a single dispute by id.
     *
     */
    public function testSaleDisputesDisputeIdGet()
    {
    }

    /**
     * Test case for saleDisputesDisputeIdMessagesGet
     *
     * Get the list of messages within dispute.
     *
     */
    public function testSaleDisputesDisputeIdMessagesGet()
    {
    }

    /**
     * Test case for saleDisputesDisputeIdMessagesPost
     *
     * Post a message.
     *
     */
    public function testSaleDisputesDisputeIdMessagesPost()
    {
    }

    /**
     * Test case for saleDisputesGet
     *
     * Get the list of the disputes.
     *
     */
    public function testSaleDisputesGet()
    {
    }
}
