<?php
/**
 * OfferContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl
 *
 * OpenAPI spec version: 1.0
 * Contact: api@allegro.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OfferContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for saleOfferContactsGet
     *
     * Get details of many contacts.
     *
     */
    public function testSaleOfferContactsGet()
    {
    }

    /**
     * Test case for saleOfferContactsIdGet
     *
     * Get contact details.
     *
     */
    public function testSaleOfferContactsIdGet()
    {
    }

    /**
     * Test case for saleOfferContactsIdPut
     *
     * Modify contact details.
     *
     */
    public function testSaleOfferContactsIdPut()
    {
    }

    /**
     * Test case for saleOfferContactsPost
     *
     * Create a new contact.
     *
     */
    public function testSaleOfferContactsPost()
    {
    }
}
