<?php
/**
 * PromotionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl
 *
 * OpenAPI spec version: 1.0
 * Contact: api@allegro.pl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PromotionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromotionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPromotionUsingPOST1
     *
     * Creates a new promotion.
     *
     */
    public function testCreatePromotionUsingPOST1()
    {
    }

    /**
     * Test case for deactivatePromotionUsingDELETE
     *
     * Deactivate promotion by its id.
     *
     */
    public function testDeactivatePromotionUsingDELETE()
    {
    }

    /**
     * Test case for getPromotionUsingGET
     *
     * Get a promotion by its id.
     *
     */
    public function testGetPromotionUsingGET()
    {
    }

    /**
     * Test case for listSellerPromotionsUsingGET1
     *
     * Get a list of promotions by user id.
     *
     */
    public function testListSellerPromotionsUsingGET1()
    {
    }
}
